### ISSUE TITLE
Question 131: Incorrect Answer

### ISSUE THREAD

**Issue by StefanusAgus** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#15]
Link to question: [link](https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers?tab=readme-ov-file#which-of-the-following-will-impact-the-price-paid-for-an-ec2-instance-choose-two)

I am not sure if my understanding is correct. For this question, I believe the correct answer would be:
(A) Instance type. and (B) The Availability Zone where the instance is provisioned.

However, (A) and (C) load balancing are marked instead. Is this an incorrect marking?

**Comment by danieldanielecki** [comment]
You're correct :)

Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/6f3b428cef8375b974bbec8bf8396662d6ddc436, thanks!
