### ISSUE TITLE
Question 243

### ISSUE THREAD

**Issue by OILikiy** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#20]
According to best practices, which of the below options is best suited for processing a large number of binary files?

The correct option should be:
-	Running EC2 instances in parallel.

**Comment by danieldanielecki** [comment]
Thanks a lot, fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/6186fb4e5e56b4bb0cde5afa18a088058d1c5dc4.
