### ISSUE TITLE
question#156 answer may needs to be revisited

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#21]
would you review question #156? with 60 Petabytes, isn't Snowmobile the best way to transfer the data to AWS? 
S3 Transfer Acceleration is good choice to migrate relatively small amount of data through internet but not idea to transfer big volume of data like 60 Petabytes. 
Much appreciation for your confirmation.

**Comment by danieldanielecki** [comment]
I'd keep it as per screenshot below, even though in one of the resources I found it's actually `Snowmobile`. It looks like there's just a minor difference :)

<img width="1105" alt="Screenshot 2024-07-08 at 17 49 13" src="https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/assets/12736263/9f76001a-3da3-4e6d-ac65-2746c1110772">

**Comment by MeowPiang** [comment]
got it. Thanks for the looking into this!
