### ISSUE TITLE
question#172 answer needs to be revisited 

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#23]
would you review question #172? 
to view the more granular data about AWS costs and usage, isn't the AWS Cost & Usage Report provides more granular data of usage and cost? while AWS Cost Exploere provides more high level overall usage and cost? 
Thanks.

**Comment by danieldanielecki** [comment]
100% correct, checked in 2 sources and fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/2ae11f51d74e768f58a8c2cbae94c2c0e08f0995

**Comment by MeowPiang** [comment]
Thanks for the confirmation.
