### ISSUE TITLE
Question 182 needs revisit its answer

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#24]
As the characteristics, one of the most benefit of using Amazon EC2 is no need to invent in hardware upfront. Would you review the answer on question 182?  should it be A? The question is asking which is NOT a characteristic of Amazon EC2. Thanks.

**Comment by danieldanielecki** [comment]
Good finding, my mistake. Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/4fed9fb07b8a1bff88d5873750a9f482d8b52ed4

**Comment by MeowPiang** [comment]
Thanks for the confirmation and correction!! Much appreciation.
