### ISSUE TITLE
question 212 needs review on the answer

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#25]
to automate the application deployment and eliminate human error, isn't AWS CodeDeploy the AWS service to use for building and automate the AWS environment? 
Would you review the answer of this question? Thanks.

**Comment by danieldanielecki** [comment]
I asked AI and indeed both are looking correct, just the current answer seems to be `more correct`, but I also found the question in https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/blob/master/practice-exam/practice-exam-5.md and the answer is `C` as well.

<img width="1060" alt="Screenshot 2024-07-07 at 20 53 15" src="https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/assets/12736263/12de5171-acc8-47f0-a5a1-323da5ad3d71">

Closing it, when you have the chance to answer any of those, please do. However, if it'll be just one, based on the same question/answer in the other exam, I'd stick with what we have.

**Comment by MeowPiang** [comment]
Got it. Thank you so much for looking into this, Daniel. Much appreciation!
