### ISSUE TITLE
question 219, answer needs to be revisited

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#26]
as question mention, it's asking example of customer's responsibility to implement 'Security IN the cloud'. 
Choice A. 'Building a schema for an application' is not related to security. 
isn't Choice D. Patch management of the underlying infrastructure an example of implementing 'security IN the cloud'? 
Please review and update with correct answer. Thanks.

**Comment by danieldanielecki** [comment]
Correct! Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/8da297846dc4414513d7572cc032e772110b5f15

**Comment by MeowPiang** [comment]
Thank you for the confirmation and correction!
