### ISSUE TITLE
question# 412 needs review for the answers. 

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#28]
The six pillars of AWS well-architected framework includes the following: 
Operational Excellence
Reliability
Security
Performance Efficiency
Cost Optimization
Sustainability. 
https://docs.aws.amazon.com/wellarchitected/latest/framework/sec-design.html
so, should the answers be BC? 
Thanks in advance for looking in this!

**Comment by danieldanielecki** [comment]
That's a no brainer. Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/b00675face2d22ccc11526342390a928e0e339d4
