### ISSUE TITLE
question 425 worth to be review

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#31]
massive economies of scale benefit the customer when AWS grows, so each individual customer would pay with less cost. 
So,..... could answer be A? Periodic price reductions as the result of Amazon's operational efficiencies
or how does option C 'The ability to scale up and down when needed' relates to the massive economies of scale? while this option looks more elasticity related? 
Thanks in advance.

**Comment by danieldanielecki** [comment]
Correct, fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/97ba5659996908774b65b0e6da260aa004891529.
