### ISSUE TITLE
question 427 answers need to be reviewed

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#32]
just google, and it seems the answer for question 427 are C. AWS Storage Gateway and E. AWS Direct Connect. 
would you mind reviewing this question. 
or would you help with how does Amazon Connect and Amazon CloudFront extent on-premises architecture to AWS Cloud? 
Thanks again!.

**Comment by danieldanielecki** [comment]
with that fix in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/c42e2936526b1fbeef740fffcb27a4c551b2e49c all your feedback has been incorporated, thank you! <3
