### ISSUE TITLE
question 431 answers need to be reviewed

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#33]
Just google it, the AWS service or feature which enhance network security by blocking requests from particular network are A. AWS WAF and E. Network ACLs. 
Two AWS services or features that can enhance network security by blocking requests from a particular network for a web application on AWS are AWS WAF (Web Application Firewall) and Network ACLs (Access Control Lists).
would you help reviewing this question and its marked answers? Thanks.

**Comment by danieldanielecki** [comment]
Yes, fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/d59e222ddd6527c44147773f11b60b0d570e1c2f.
