### ISSUE TITLE
question 438

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#34]
should answer be BD?   isn't D. Region part of the component of AWS Global infrastructure? 
Thank you in advance for reviewing the question with marked answer.

**Comment by danieldanielecki** [comment]
It should be & is fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/1d8169a1c13abff9beac2eda5875ff99c8d34e0e.
