### ISSUE TITLE
question 441

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#35]
would you review the marked answer of question 441? 
per brainly searched from google, costs that can be included are project management, antivirus software licensing, and data center security. but it stated the correct answer is C. Data Center Security. In addition, Data Center Security seems more relevant to the 'Total Ownership Cost'. 
Many thanks in advance.

**Comment by danieldanielecki** [comment]
Absolutely... fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/71ea0fcd424b1020c4950fac43bd74ab1a20a57f.
