### ISSUE TITLE
question 454 needs review with its marked answer

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#36]
would you mind reviewing question 454 with its answer? As AWS -managed compute service, C. AWS Lambda seems a more correct answer than B Amazon EC2. While Lambda is a server less compute service. 
Many Thanks in advance.

**Comment by danieldanielecki** [comment]
In my opinion both answers are correct, please refer to https://docs.aws.amazon.com/decision-guides/latest/compute-on-aws-how-to-choose/choosing-aws-compute-service.html & Copilot below.

However, based on what I could find on https://www.coursehero.com/file/p44cps11/Topic-1-Question-177-Which-of-the-following-is-an-AWS-managed-compute-service-A/ this question requires just one answer... quite silly tbh, but I'll keep it as is seeing the same question elsewhere.

<img width="1109" alt="Screenshot 2024-07-13 at 21 51 58" src="https://github.com/user-attachments/assets/4881a236-cd74-4283-8691-c988c6fa4435">
