### ISSUE TITLE
question 458 question needs review its marked answer

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#37]
Amazon Macie is a data security service that uses machine learning (ML) and pattern matching to discover and help protect your sensitive data. so... should the answer be B instead of A? 
Thanks for looking into this.

**Comment by danieldanielecki** [comment]
Thank you for the finding. It's fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/812dee5e24dfb6d20c5f3a163a5306d9b565f45b.
