### ISSUE TITLE
question # 472 needs review on the marked answers

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#38]
as searched result on google, some resources shows the the tools assist with estimating costs are the A. Detailed billing report, C. AWS simigple monthly calculator and D. AWS Total Cost of ownership (TCO) calculator. 
would you mind reviewing the marked answer and see if it's ACD instead of BCD instead? Thank you so much.

**Comment by danieldanielecki** [comment]
A detailed billing report isn't the right tool. That's just a report, not a tool.
The correct answers stay; please find resources for that.

<img width="1087" alt="Screenshot 2024-07-13 at 21 39 52" src="https://github.com/user-attachments/assets/6d9b11b4-a0b0-49d3-b630-8059d8678c10">
<img width="881" alt="Screenshot 2024-07-13 at 21 40 12" src="https://github.com/user-attachments/assets/f0ebcecb-f122-435d-af29-1e2a842cee68">
<img width="1084" alt="Screenshot 2024-07-13 at 21 40 22" src="https://github.com/user-attachments/assets/cf5830a9-9183-49da-9e54-0c623f17e3d7">

https://www.coursehero.com/file/p6tt7egm/Question-17-Topic-1-Which-AWS-tools-assist-with-estimating-costs-Choose-three-A/
