### ISSUE TITLE
question#478 needs review on the answers

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#39]
While the question is asking for the services which can gather inforamtion about AWS Account activity, Amazon CloudFront doesn't seem to have this function. AWS CloudTrail and Amazon Cloud Watch seems more having this functions. 
Would you mind giving it a revisit and confirm the answer? Many Thanks again.

**Comment by danieldanielecki** [comment]
You are 100% correct, fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/e51a6d45d1904c08a4f26aea6a7c96685eaad44a.
