### ISSUE TITLE
Question 509 needs review on the answers marked

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#41]
on question 5.9, it seems option C ' They are capable of handling constant changes in network traffic patterns.' makes more sense rather than option B. Searched on Google with some resources, which marked option C as correct answers. Would you minding reviewing it and see if C is more accurate? Thanks a lot.

**Comment by danieldanielecki** [comment]
Yes, of course. Thank you for contribution, adjusted in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/bb688f86b88aa51d663970057440ad3f38d9536f.
