### ISSUE TITLE
question #531 needs review on its marked answer

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#42]
referring to AWS support reference: 
https://aws.amazon.com/premiumsupport/plans/
it looks like Concierge Team is the service which requires at least Enterprise Onramp support level. 
Cannot find any source mentioning Amazon Connect requires at least Enterprise support level. 
Would you reviewing this question and see if the marked answer is correct? Thanks a lot.

**Comment by danieldanielecki** [comment]
It was a bad mistake, sorry for that. Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/899db09d1c3464ffa6fb1843366dc06d9c370889.
