### ISSUE TITLE
Question 539 needs review on the marked answer

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#43]
As a service or tool provides detailed reports on estimated cost, the answer is probably either A or B. 
AWS Budgets is the service to help monitoring usage and control cost per understanding. 
Would you review the question with its marked answer? Thanks again!

**Comment by danieldanielecki** [comment]
I must have missed that one, of course! Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/a7f234f4a66cf6b7642082326e4256c812fc0eb5.
