### ISSUE TITLE
Question 542 needs review on the marked answer

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#44]
the answer for this question may be arguable between C AWS Trusted Advisor and D AWS Discussion Forums. While AWS Trusted Advisor at basic support level only provide basic checks, but basic support provides service including discussion forum. 
"AWS Basic Support offers all AWS customers access to our Resource Center, Service Health Dashboard, Product FAQs, and Discussion Forums – at no additional charge. "
Would you review this question and see if the current marked answer still sustains? Thank you so much.

**Comment by danieldanielecki** [comment]
Nope @MeowPiang, this one is correct and it's `AWS Trusted Advisor` :)

**Comment by danieldanielecki** [comment]
PS. You can also use https://education.ditectrev.com and when you have Ollama running it'll generate explanations as described in https://github.com/Ditectrev/Practice-Exams-Platform#explanations. For some of the questions it'd clarify you :)

**Comment by danieldanielecki** [comment]
<img width="1067" alt="Screenshot 2024-07-11 at 13 46 44" src="https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/assets/12736263/ddc84bbe-f08a-4a60-8b96-467f68ff8c47">
<img width="1071" alt="Screenshot 2024-07-11 at 13 46 53" src="https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/assets/12736263/f10a0049-f1a8-45e2-a284-30749580d218">
