### ISSUE TITLE
question 556 needs review and further evaluation for its answers

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#45]
The options in this question seems a little bit ambiguous, so it may be arguable which is the correct answer. 
Option A seems unlikely the answer while AWS is responsible for security ON the AWS Cloud, the customers are responsible for security in the Cloud. 
regarding the other options..... B and C are possible.. and B is probably more likely the answer. 
Just a thought it will be great if you would revisit this one. Thanks a lot!

**Comment by danieldanielecki** [comment]
I did some research and agreed with `No long-term contract is required.` is the most accurate one.

Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/bba53536d42ef5a60e24db496ade6235d6fa0c38.
