### ISSUE TITLE
question #561 may worth to be revisited

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#46]
searched resource 
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/blob/master/practice-exam/practice-exam-12.md
C , D seems more correct answer than C E, 
while per my understanding, AWS does not manage the security patching on the application. 
Thank you for revisiting!

**Comment by danieldanielecki** [comment]
I also agree, D makes a bit of more sense in this question than E. Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/957a258b2b8e573cfeb11765c10f8b7ec81ce97e.
