### ISSUE TITLE
question # 583 marked answer needs review

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#47]
on question 584, option E seems more accurate than option C, while the patching of hypervisor is managed by AWS, and the security group is configured by the customer if I understand it right. Would you help with revisiting the marked answer? Much appreciation.

**Comment by danieldanielecki** [comment]
It was a difficult one, but you're correct. Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/92da652e94ddffdea4f7edd860ba97a4c126de9f.
