### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by anshuparik** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#53]
Much AWS services provide a way to extend an on-premises architecture to the AWS Cloud? (Select TWO)
 Amazon EBS.
 AWS Direct Connect.
 Amazon CloudFront.
 AWS Storage Gateway.
 Amazon Connect.
 
 it should be **Which** AWS services provide a way to extend an on-premises architecture to the AWS Cloud? (Select TWO)

**Comment by danieldanielecki** [comment]
Part of https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/pull/55, will be merged there!

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/pull/55/, amazing job!! Thank you ;-)
