### ISSUE TITLE
Issue with answer

### ISSUE THREAD

**Issue by anshuparik** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#56]
A company is migrating its on-premises database to Amazon RDS. What should the company do to ensure Amazon RDS costs are kept to a minimum?
 - Right-size before and after migration.
 - Use a Multi-Region Active-Passive architecture.
 - Combine On-demand Capacity Reservations with Saving Plans.
 - Use a Multi-Region Active-Active architecture.

- Correct Answer - Right-size before and after migration.

**Comment by danieldanielecki** [comment]
@anshuparik correct, thank you. It's fixed!
