### ISSUE TITLE
The answer is not available

### ISSUE THREAD

**Issue by anshuparik** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#59]
Which is the MINIMUM AWS Support plan that allows for one-hour target response time for support cases?
 Enterprise.
 Business.
 Developer
 Basic

The answer is not available  for this questions

**Comment by danieldanielecki** [comment]
Part of https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/pull/55/, thank you!

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/pull/55/, amazing job!! Thank you ;-)
